##Instrucciones: Tarea Sofía Ayala
1. Genera una lista que consista de  20  números que estén en el intervalo  [−1,1] . Llámala Lista_1.
2. Genera una lista que consista de  20  números que sean enteros en el intervalo  [1500,3000] . Llámala Lista_2.
3. Crea un diccionario cuyas llaves sean "CapSmall" y "CapLarge" y sus valores sean la Lista_1 y Lista_2, respectivamente.
4. Crea un DataFrame a partir del diccionario del punto anterior. Llámalo df.
5. Reindexa los índices poniendo Año 1 ,...,  Año 20.
6. Realiza una explicación de la estadística descriptiva de tu DataFrame.
7. ¿Cuál es el valor mínimo de la columna "CapSmall"?
8. ¿Cuál es "CapLarge" promedio del año 10 al año 20.
9. Realiza una gráfica de Año contra "CapLarge".
10. Muestra el DataFrame que obtienes si tomas aquellos valores de "CapLarge" mayores a  2000 . ¿Cuál es la dimensión (shape) de tu nueva base de datos?

In [97]:
import numpy as np

In [ ]:
#Ejercicio 1
Lista_1=np.random.uniform(low=-1,high=1,size=20)
Lista_1

array([-0.08669225,  0.75867411, -0.99863686, -0.22268524,  0.46756899,
       -0.328011  , -0.11981358,  0.66128917, -0.1454657 , -0.8526039 ,
        0.02375732,  0.40307946,  0.49866593,  0.31973747, -0.68739927,
        0.18136701,  0.35862795,  0.69022189,  0.65912101,  0.9277413 ])

In [ ]:
#Ejercicio 2
Lista_2=np.random.randint(low=1500,high=3000, size=20)
Lista_2

array([2138, 2978, 1988, 2036, 1736, 2400, 2928, 2625, 2426, 2706, 2170,
       2972, 2966, 2751, 1688, 1659, 1572, 2934, 1947, 2941])

In [98]:
#Ejercicio 3
Diccionario={"CapSmall":[-0.08669225,  0.75867411, -0.99863686, -0.22268524,  0.46756899,
       -0.328011  , -0.11981358,  0.66128917, -0.1454657 , -0.8526039 ,
        0.02375732,  0.40307946,  0.49866593,  0.31973747, -0.68739927,
        0.18136701,  0.35862795,  0.69022189,  0.65912101,  0.9277413 ],
             "CapLarge":[2138, 2978, 1988, 2036, 1736, 2400, 2928, 2625, 2426, 2706, 2170,
       2972, 2966, 2751, 1688, 1659, 1572, 2934, 1947, 2941]}
Diccionario

{'CapSmall': [-0.08669225,
  0.75867411,
  -0.99863686,
  -0.22268524,
  0.46756899,
  -0.328011,
  -0.11981358,
  0.66128917,
  -0.1454657,
  -0.8526039,
  0.02375732,
  0.40307946,
  0.49866593,
  0.31973747,
  -0.68739927,
  0.18136701,
  0.35862795,
  0.69022189,
  0.65912101,
  0.9277413],
 'CapLarge': [2138,
  2978,
  1988,
  2036,
  1736,
  2400,
  2928,
  2625,
  2426,
  2706,
  2170,
  2972,
  2966,
  2751,
  1688,
  1659,
  1572,
  2934,
  1947,
  2941]}

In [99]:
import pandas as pd
#Ejercicio 4 y 5
df=pd.DataFrame(Diccionario,index=["Año 1","Año 2","Año 3","Año 4","Año 5","Año 6","Año 7","Año 8","Año 9","Año 10","Año 11","Año 12","Año 13","Año 14","Año 15","Año 16","Año 17","Año 18","Año 19","Año 20"])
df

        CapSmall  CapLarge
Año 1  -0.086692      2138
Año 2   0.758674      2978
Año 3  -0.998637      1988
Año 4  -0.222685      2036
Año 5   0.467569      1736
Año 6  -0.328011      2400
Año 7  -0.119814      2928
Año 8   0.661289      2625
Año 9  -0.145466      2426
Año 10 -0.852604      2706
Año 11  0.023757      2170
Año 12  0.403079      2972
Año 13  0.498666      2966
Año 14  0.319737      2751
Año 15 -0.687399      1688
Año 16  0.181367      1659
Año 17  0.358628      1572
Año 18  0.690222      2934
Año 19  0.659121      1947
Año 20  0.927741      2941

In [100]:
#Ejercicio 6
df.describe()

        CapSmall     CapLarge
count  20.000000    20.000000
mean    0.125427  2378.050000
std     0.550636   508.260447
min    -0.998637  1572.000000
25%    -0.164771  1977.750000
50%     0.250552  2413.000000
75%     0.538780  2929.500000
max     0.927741  2978.000000

In [101]:
#Ejercicio 7: ¿Cuál es el valor mínimo de la columna "CapSmall"?
#R= -0.998637
#Este valor lo saque de la tabla de estadística (min)

In [102]:
#Ejercicio 8:
CapLarge_promedio=df.iloc[10:20]
CapLarge_promedio=CapLarge_promedio.drop(columns="CapSmall")
CapLarge_promedio

        CapLarge
Año 11      2170
Año 12      2972
Año 13      2966
Año 14      2751
Año 15      1688
Año 16      1659
Año 17      1572
Año 18      2934
Año 19      1947
Año 20      2941

In [103]:
#"CapLarge" promedio del año 10 al año 20
CapLarge_promedio.mean()

CapLarge    2360.0
dtype: float64

In [104]:
#Ejercicio 9
df=df.drop(columns="CapSmall")

In [105]:
print(df)

        CapLarge
Año 1       2138
Año 2       2978
Año 3       1988
Año 4       2036
Año 5       1736
Año 6       2400
Año 7       2928
Año 8       2625
Año 9       2426
Año 10      2706
Año 11      2170
Año 12      2972
Año 13      2966
Año 14      2751
Año 15      1688
Año 16      1659
Año 17      1572
Año 18      2934
Año 19      1947
Año 20      2941

In [106]:
#Ejercicio 10
filtro = df["CapLarge"] > 2000
nueva_df = df[filtro]
nueva_df

        CapLarge
Año 1       2138
Año 2       2978
Año 4       2036
Año 6       2400
Año 7       2928
Año 8       2625
Año 9       2426
Año 10      2706
Año 11      2170
Año 12      2972
Año 13      2966
Año 14      2751
Año 18      2934
Año 20      2941

In [107]:
nueva_df.shape #¿Cuál es la dimensión (shape) de tu nueva base de datos?

(14, 1)